/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.bonvino;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
/**
 *
 * @author Chiara
 */
public class InterfazRegistroBonVino extends javax.swing.JFrame {

    /**
     * Creates new form InterfazRegistroBonVino
     */
    public InterfazRegistroBonVino() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        fondoRojo = new javax.swing.JPanel();
        fondoBlanco = new com.mycompany.bonvino.PanelRound();
        ImagenCheck = new javax.swing.JLabel();
        TextoRegistro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(166, 57, 57));
        setMinimumSize(new java.awt.Dimension(1080, 720));

        fondoRojo.setBackground(new java.awt.Color(166, 57, 57));
        fondoRojo.setMaximumSize(new java.awt.Dimension(1080, 321321));
        fondoRojo.setMinimumSize(new java.awt.Dimension(1080, 720));

        fondoBlanco.setBackground(new java.awt.Color(244, 237, 222));
        fondoBlanco.setMinimumSize(new java.awt.Dimension(880, 480));
        fondoBlanco.setRoundBottomLeft(30);
        fondoBlanco.setRoundBottomRight(30);
        fondoBlanco.setRoundTopLeft(30);
        fondoBlanco.setRoundTopRight(30);

        ImagenCheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check.png"))); // NOI18N

        TextoRegistro.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        TextoRegistro.setForeground(new java.awt.Color(102, 0, 0));
        TextoRegistro.setText("¡Se generó correctamente!");

        javax.swing.GroupLayout fondoBlancoLayout = new javax.swing.GroupLayout(fondoBlanco);
        fondoBlanco.setLayout(fondoBlancoLayout);
        fondoBlancoLayout.setHorizontalGroup(
            fondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoBlancoLayout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addComponent(TextoRegistro)
                .addGap(162, 162, 162))
            .addGroup(fondoBlancoLayout.createSequentialGroup()
                .addGap(351, 351, 351)
                .addComponent(ImagenCheck)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondoBlancoLayout.setVerticalGroup(
            fondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoBlancoLayout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addComponent(TextoRegistro)
                .addGap(18, 18, 18)
                .addComponent(ImagenCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );

        javax.swing.GroupLayout fondoRojoLayout = new javax.swing.GroupLayout(fondoRojo);
        fondoRojo.setLayout(fondoRojoLayout);
        fondoRojoLayout.setHorizontalGroup(
            fondoRojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoRojoLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(fondoBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        fondoRojoLayout.setVerticalGroup(
            fondoRojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoRojoLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(fondoBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        getContentPane().add(fondoRojo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistroBonVino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistroBonVino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistroBonVino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistroBonVino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazRegistroBonVino().setVisible(true);
            }
        });
    }
    private void SetImageLabel (JLabel labelName, String root){
        ImageIcon image = new ImageIcon (root);
        Icon icon = new ImageIcon(
            image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT));
        labelName.setIcon(icon);
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImagenCheck;
    private javax.swing.JLabel TextoRegistro;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.mycompany.bonvino.PanelRound fondoBlanco;
    private javax.swing.JPanel fondoRojo;
    // End of variables declaration//GEN-END:variables
}
